export interface GiftPreset {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  tier: 'mini' | 'medium' | 'luxury';
  emoji: string;
}

export const DEFAULT_GIFT_PRESETS: GiftPreset[] = [
  // Mini Tier (10 - 200 coins)
  {
    id: 'rose',
    name: 'Red Rose',
    description: 'Classic romantic red rose',
    price: 10,
    image: '/assets/gifts/rose.png',
    tier: 'mini',
    emoji: '🌹',
  },
  {
    id: 'heart',
    name: 'Sparkling Heart',
    description: 'Sparkling heart full of love',
    price: 20,
    image: '/assets/gifts/heart.png',
    tier: 'mini',
    emoji: '💖',
  },
  {
    id: 'star',
    name: 'Golden Star',
    description: 'Shining golden superstar',
    price: 50,
    image: '/assets/gifts/star.png',
    tier: 'mini',
    emoji: '⭐',
  },
  {
    id: 'party',
    name: 'Party Popper',
    description: 'Celebration and confetti popper',
    price: 50,
    image: '/assets/gifts/party.png',
    tier: 'mini',
    emoji: '🎉',
  },
  {
    id: 'teddy',
    name: 'Teddy Bear',
    description: 'Cute fluffy teddy bear',
    price: 100,
    image: '/assets/gifts/teddy.png',
    tier: 'mini',
    emoji: '🧸',
  },
  {
    id: 'cake',
    name: 'Birthday Cake',
    description: 'Sweet celebration cake',
    price: 150,
    image: '/assets/gifts/cake.png',
    tier: 'mini',
    emoji: '🎂',
  },
  {
    id: 'bouquet',
    name: 'Flower Bouquet',
    description: 'Elegant bouquet of flowers',
    price: 200,
    image: '/assets/gifts/bouquet.png',
    tier: 'mini',
    emoji: '💐',
  },

  // Medium Tier (300 - 2,000 coins)
  {
    id: 'fire',
    name: 'Fire Flame',
    description: 'Hype energetic fire flame',
    price: 300,
    image: '/assets/gifts/fire.png',
    tier: 'medium',
    emoji: '🔥',
  },
  {
    id: 'magic_wand',
    name: 'Magic Wand',
    description: 'Magical sparkling star wand',
    price: 400,
    image: '/assets/gifts/magic_wand.png',
    tier: 'medium',
    emoji: '🪄',
  },
  {
    id: 'diamond',
    name: 'Luxury Diamond',
    description: 'Precious sparkling diamond',
    price: 500,
    image: '/assets/gifts/diamond.png',
    tier: 'medium',
    emoji: '💎',
  },
  {
    id: 'trophy',
    name: 'Golden Trophy',
    description: 'Champion winner gold trophy',
    price: 800,
    image: '/assets/gifts/trophy.png',
    tier: 'medium',
    emoji: '🏆',
  },
  {
    id: 'crown',
    name: 'Royal Crown',
    description: 'Majestic royal golden crown',
    price: 1000,
    image: '/assets/gifts/crown.png',
    tier: 'medium',
    emoji: '👑',
  },
  {
    id: 'ring',
    name: 'Diamond Ring',
    description: 'Luxury engagement diamond ring',
    price: 1500,
    image: '/assets/gifts/ring.png',
    tier: 'medium',
    emoji: '💍',
  },
  {
    id: 'crystal_ball',
    name: 'Crystal Ball',
    description: 'Mysterious magical crystal ball',
    price: 1800,
    image: '/assets/gifts/crystal_ball.png',
    tier: 'medium',
    emoji: '🔮',
  },
  {
    id: 'guitar',
    name: 'Rock Guitar',
    description: 'Electric rock star guitar',
    price: 2000,
    image: '/assets/gifts/guitar.png',
    tier: 'medium',
    emoji: '🎸',
  },

  // Luxury VIP Tier (5,000 - 50,000 coins)
  {
    id: 'supercar',
    name: 'Supercar',
    description: 'Ultra fast luxury sports car',
    price: 5000,
    image: '/assets/gifts/supercar.png',
    tier: 'luxury',
    emoji: '🏎️',
  },
  {
    id: 'rocket',
    name: 'Space Rocket',
    description: 'Flying supersonic space rocket',
    price: 10000,
    image: '/assets/gifts/rocket.png',
    tier: 'luxury',
    emoji: '🚀',
  },
  {
    id: 'airplane',
    name: 'Private Jet',
    description: 'VIP luxury private airplane',
    price: 15000,
    image: '/assets/gifts/airplane.png',
    tier: 'luxury',
    emoji: '✈️',
  },
  {
    id: 'yacht',
    name: 'Luxury Yacht',
    description: 'Ocean luxury cruise yacht',
    price: 20000,
    image: '/assets/gifts/yacht.png',
    tier: 'luxury',
    emoji: '🛥️',
  },
  {
    id: 'unicorn',
    name: 'Mythic Unicorn',
    description: 'Magical fairytale unicorn',
    price: 25000,
    image: '/assets/gifts/unicorn.png',
    tier: 'luxury',
    emoji: '🦄',
  },
  {
    id: 'lion',
    name: 'Golden Lion',
    description: 'The king of the jungle lion',
    price: 30000,
    image: '/assets/gifts/lion.png',
    tier: 'luxury',
    emoji: '🦁',
  },
  {
    id: 'castle',
    name: 'Royal Castle',
    description: 'Magnificent fairytale castle',
    price: 40000,
    image: '/assets/gifts/castle.png',
    tier: 'luxury',
    emoji: '🏰',
  },
  {
    id: 'dragon',
    name: 'Ancient Dragon',
    description: 'Legendary mythical golden dragon',
    price: 50000,
    image: '/assets/gifts/dragon.png',
    tier: 'luxury',
    emoji: '🐉',
  },
];
