export interface StorePreset {
  id: string;
  name: string;
  description: string;
  type: 'frame' | 'entry_effect' | 'chat_bubble';
  price: number;
  durationDays: number;
  image: string;
  animation?: string;
  emoji: string;
}

export const DEFAULT_STORE_PRESETS: StorePreset[] = [
  // 1. Avatar Frames (إطارات الصور الشخصية)
  {
    id: 'frame_royal_gold',
    name: 'Royal Gold Frame',
    description: 'Majestic golden circular frame with a royal crown and glowing accents',
    type: 'frame',
    price: 1500,
    durationDays: 30,
    image: '/assets/store/frame_royal_gold.svg',
    emoji: '👑',
  },
  {
    id: 'frame_cyber_neon',
    name: 'Cyber Neon Frame',
    description: 'Futuristic glowing cyan and magenta cyberpunk neon ring',
    type: 'frame',
    price: 1200,
    durationDays: 30,
    image: '/assets/store/frame_cyber_neon.svg',
    emoji: '⚡',
  },
  {
    id: 'frame_blazing_flame',
    name: 'Blazing Flame Frame',
    description: 'Intense fiery flame aura border with glowing fire bursts',
    type: 'frame',
    price: 1800,
    durationDays: 30,
    image: '/assets/store/frame_blazing_flame.svg',
    emoji: '🔥',
  },
  {
    id: 'frame_diamond_crystal',
    name: 'Diamond Crystal Frame',
    description: 'Shining crystalline diamond facets with sparkle particle effects',
    type: 'frame',
    price: 2500,
    durationDays: 30,
    image: '/assets/store/frame_diamond_crystal.svg',
    emoji: '💎',
  },
  {
    id: 'frame_sakura_blossom',
    name: 'Sakura Blossom Frame',
    description: 'Charming pastel pink sakura petals and blooming cherry blossom ring',
    type: 'frame',
    price: 1000,
    durationDays: 30,
    image: '/assets/store/frame_sakura_blossom.svg',
    emoji: '🌸',
  },
  {
    id: 'frame_cosmic_galaxy',
    name: 'Cosmic Galaxy Frame',
    description: 'Deep purple cosmic nebula ring with twinkling galactic stars',
    type: 'frame',
    price: 2000,
    durationDays: 30,
    image: '/assets/store/frame_cosmic_galaxy.svg',
    emoji: '🌌',
  },

  // 2. Live Stream Entry Effects (مؤثرات الدخول للبث - متحركة 3D Animated)
  {
    id: 'entry_supercar',
    name: 'Supercar VIP Entry',
    description: 'Arrive in the live stream with a roar in a luxury racing supercar with neon underglow and exhaust flames',
    type: 'entry_effect',
    price: 5000,
    durationDays: 30,
    image: '/assets/store/entry_supercar.png',
    animation: '/assets/store/animations/entry_supercar.webp',
    emoji: '🏎️',
  },
  {
    id: 'entry_rocket',
    name: 'Space Rocket Entry',
    description: 'Blast off into the live stream with a supersonic space rocket with roaring flame plumes and sparks',
    type: 'entry_effect',
    price: 8000,
    durationDays: 30,
    image: '/assets/store/entry_rocket.png',
    animation: '/assets/store/animations/entry_rocket.webp',
    emoji: '🚀',
  },
  {
    id: 'entry_jet',
    name: 'Private Jet Entry',
    description: 'High-roller VIP arrival on a supersonic private jet with electric cyan afterburners and shockwave rings',
    type: 'entry_effect',
    price: 10000,
    durationDays: 30,
    image: '/assets/store/entry_jet.png',
    animation: '/assets/store/animations/entry_jet.webp',
    emoji: '✈️',
  },
  {
    id: 'entry_dragon',
    name: 'Ancient Dragon Entry',
    description: 'Summon the legendary mythical golden dragon upon your entrance with celestial aura and golden fire',
    type: 'entry_effect',
    price: 15000,
    durationDays: 30,
    image: '/assets/store/entry_dragon.png',
    animation: '/assets/store/animations/entry_dragon.webp',
    emoji: '🐉',
  },
  {
    id: 'entry_comet',
    name: 'Shooting Comet Entry',
    description: 'Streak across the screen like a glowing cosmic meteor comet trailing nebula stardust and flares',
    type: 'entry_effect',
    price: 6000,
    durationDays: 30,
    image: '/assets/store/entry_comet.png',
    animation: '/assets/store/animations/entry_comet.webp',
    emoji: '☄️',
  },
  {
    id: 'entry_helicopter',
    name: 'VIP Helicopter Entry',
    description: 'Executive aerial helicopter entrance with rotating rotor blur, searchlight, and flashing beacon',
    type: 'entry_effect',
    price: 7500,
    durationDays: 30,
    image: '/assets/store/entry_helicopter.png',
    animation: '/assets/store/animations/entry_helicopter.webp',
    emoji: '🚁',
  },

  // 3. Chat Bubbles (فقاعات الدردشة المميزة)
  {
    id: 'bubble_gold_vip',
    name: 'Gold VIP Chat Bubble',
    description: 'Luxurious metallic gold gradient speech bubble with royal crown badge',
    type: 'chat_bubble',
    price: 800,
    durationDays: 30,
    image: '/assets/store/bubble_gold_vip.svg',
    emoji: '💬',
  },
  {
    id: 'bubble_neon_cyber',
    name: 'Neon Cyber Chat Bubble',
    description: 'Cyberpunk electric cyan glowing bubble with futuristic tech border',
    type: 'chat_bubble',
    price: 600,
    durationDays: 30,
    image: '/assets/store/bubble_neon_cyber.svg',
    emoji: '🌐',
  },
  {
    id: 'bubble_fire_flame',
    name: 'Fire Flame Chat Bubble',
    description: 'Hot fiery gradient speech bubble with flickering flame tail',
    type: 'chat_bubble',
    price: 700,
    durationDays: 30,
    image: '/assets/store/bubble_fire_flame.svg',
    emoji: '🔥',
  },
  {
    id: 'bubble_romantic_love',
    name: 'Sweet Love Chat Bubble',
    description: 'Sweet pastel pink speech bubble with romantic heart embellishments',
    type: 'chat_bubble',
    price: 500,
    durationDays: 30,
    image: '/assets/store/bubble_romantic_love.svg',
    emoji: '💖',
  },
  {
    id: 'bubble_cosmic_purple',
    name: 'Galaxy Nebula Chat Bubble',
    description: 'Deep violet and starry gradient chat bubble with star sparkles',
    type: 'chat_bubble',
    price: 600,
    durationDays: 30,
    image: '/assets/store/bubble_cosmic_purple.svg',
    emoji: '✨',
  },
];
